apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress-apache-nginx
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: nginx-deployment
          servicePort: 30003
      - path: /nginx
        backend:
          serviceName: nginx-service
          servicePort: 80
